package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/fleet-service/internal/config"
	"github.com/fleet-service/internal/consumers"
	"github.com/fleet-service/internal/database"
	"github.com/fleet-service/internal/handlers"
	"github.com/fleet-service/internal/services"
	"github.com/gin-gonic/gin"
	amqp "github.com/rabbitmq/amqp091-go"

	_ "github.com/fleet-service/docs" // docs is generated by Swag CLI
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Fleet Service API
// @version 1.0
// @description API para gestión de flota de camiones, conductores y turnos
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email soporte@latacunga-clean.com

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8084
// @BasePath /api/v1

// @schemes http https
func main() {
	log.Println("🚀 Iniciando Fleet Service...")

	// 1. Cargar configuración
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatalf("❌ Error al cargar configuración: %v", err)
	}

	// 2. Conectar a la base de datos
	if err := database.Connect(&cfg.Database); err != nil {
		log.Fatalf("❌ Error al conectar a la base de datos: %v", err)
	}
	defer database.Close()

	// 3. Ejecutar migraciones
	if err := database.Migrate(); err != nil {
		log.Fatalf("❌ Error al ejecutar migraciones: %v", err)
	}

	// 4. Conectar a RabbitMQ
	rabbitConn, err := amqp.Dial(cfg.RabbitMQ.URL)
	if err != nil {
		log.Fatalf("❌ Error al conectar con RabbitMQ: %v", err)
	}
	defer rabbitConn.Close()
	log.Println("✓ Conectado a RabbitMQ")

	// 5. Inicializar Event Publisher
	publisher, err := services.NewEventPublisher(cfg.RabbitMQ.URL, cfg.Exchanges)
	if err != nil {
		log.Fatalf("❌ Error al inicializar EventPublisher: %v", err)
	}
	defer publisher.Close()

	// 6. Inicializar Allocation Service
	allocationService := services.NewAllocationService(publisher)

	// 7. Inicializar Fleet RPC Consumer (Request-Reply pattern)
	fleetRPCConsumer, err := consumers.NewFleetRPCConsumer(
		rabbitConn,
		allocationService,
		publisher,
	)
	if err != nil {
		log.Fatalf("❌ Error al crear FleetRPCConsumer: %v", err)
	}
	defer fleetRPCConsumer.Close()

	if err := fleetRPCConsumer.Start(); err != nil {
		log.Fatalf("❌ Error al iniciar FleetRPCConsumer: %v", err)
	}
	log.Println("✓ Fleet RPC Consumer iniciado (Request-Reply pattern)")

	// 7.2 Inicializar Consumers legacy
	identityConsumer, err := consumers.NewIdentityConsumer(
		rabbitConn,
		cfg.Queues.IdentitySync,
		cfg.Exchanges.IdentityManagement,
	)
	if err != nil {
		log.Fatalf("❌ Error al crear IdentityConsumer: %v", err)
	}
	defer identityConsumer.Close()

	resourceConsumer, err := consumers.NewResourceConsumer(
		rabbitConn,
		cfg.Queues.ResourceRequests,
		cfg.Exchanges.PlanningScheduler,
		allocationService,
		publisher,
	)
	if err != nil {
		log.Fatalf("❌ Error al crear ResourceConsumer: %v", err)
	}
	defer resourceConsumer.Close()

	workorderConsumer, err := consumers.NewWorkorderConsumer(
		rabbitConn,
		cfg.Queues.WorkorderUpdates,
		cfg.Exchanges.OperationsWorkorders,
		allocationService,
	)
	if err != nil {
		log.Fatalf("❌ Error al crear WorkorderConsumer: %v", err)
	}
	defer workorderConsumer.Close()

	// 8. Iniciar consumers
	if err := identityConsumer.Start(); err != nil {
		log.Fatalf("❌ Error al iniciar IdentityConsumer: %v", err)
	}

	if err := resourceConsumer.Start(); err != nil {
		log.Fatalf("❌ Error al iniciar ResourceConsumer: %v", err)
	}

	if err := workorderConsumer.Start(); err != nil {
		log.Fatalf("❌ Error al iniciar WorkorderConsumer: %v", err)
	}

	log.Println("✓ Todos los consumers están activos")

	// 9. Configurar Gin
	gin.SetMode(cfg.Server.GinMode)
	router := gin.Default()

	// Health check
	// @Summary Health Check
	// @Description Verifica el estado del servicio
	// @Tags Health
	// @Produce json
	// @Success 200 {object} map[string]string
	// @Router /health [get]
	router.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"service": "fleet-service",
			"status":  "healthy",
		})
	})

	// 10. Registrar rutas de API
	apiV1 := router.Group("/api/v1")
	
	// Rutas de turnos
	shiftHandler := handlers.NewShiftHandler(publisher)
	shiftHandler.RegisterRoutes(apiV1)

	// Rutas de camiones (CRUD)
	truckService := services.NewTruckService()
	truckHandler := handlers.NewTruckHandler(truckService)
	trucksGroup := apiV1.Group("/trucks")
	{
		trucksGroup.POST("", truckHandler.CreateTruck)
		trucksGroup.GET("", truckHandler.ListTrucks)
		trucksGroup.GET("/:id", truckHandler.GetTruck)
		trucksGroup.PUT("/:id", truckHandler.UpdateTruck)
		trucksGroup.DELETE("/:id", truckHandler.DeleteTruck)
	}

	// Rutas de conductores (CRUD)
	driverService := services.NewDriverService()
	driverHandler := handlers.NewDriverHandler(driverService)
	driversGroup := apiV1.Group("/drivers")
	{
		driversGroup.GET("/available", driverHandler.GetAvailableDrivers) // Debe ir antes de /:id
		driversGroup.GET("", driverHandler.ListDrivers)
		driversGroup.GET("/:id", driverHandler.GetDriver)
		driversGroup.PUT("/:id", driverHandler.UpdateDriver)
		driversGroup.DELETE("/:id", driverHandler.DeleteDriver)
		driversGroup.PUT("/:id/profile", driverHandler.UpdateOperatorProfile)
		driversGroup.GET("/:id/stats", driverHandler.GetDriverStats)
	}

	// Swagger documentation
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	log.Println("📚 Documentación Swagger disponible en: http://localhost:" + cfg.Server.Port + "/swagger/index.html")

	// 11. Iniciar servidor HTTP en goroutine
	go func() {
		addr := ":" + cfg.Server.Port
		log.Printf("🌐 Servidor HTTP escuchando en %s", addr)
		if err := router.Run(addr); err != nil {
			log.Fatalf("❌ Error al iniciar servidor HTTP: %v", err)
		}
	}()

	// 12. Graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Println("🛑 Apagando Fleet Service...")
	log.Println("✓ Fleet Service detenido correctamente")
}
