// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "soporte@latacunga-clean.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/drivers": {
            "get": {
                "description": "Obtiene la lista de todos los conductores con filtros opcionales",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conductores"
                ],
                "summary": "Listar conductores",
                "parameters": [
                    {
                        "enum": [
                            "OFFLINE",
                            "DISPONIBLE",
                            "OCUPADO"
                        ],
                        "type": "string",
                        "description": "Filtrar por estado",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtrar por zona preferida",
                        "name": "zone_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de conductores",
                        "schema": {
                            "$ref": "#/definitions/handlers.ListDriversResponse"
                        }
                    },
                    "400": {
                        "description": "Parámetros inválidos",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/drivers/available": {
            "get": {
                "description": "Lista conductores con turno activo y estado disponible",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conductores"
                ],
                "summary": "Obtener conductores disponibles",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filtrar por zona preferida",
                        "name": "zone_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de conductores disponibles",
                        "schema": {
                            "$ref": "#/definitions/handlers.ListDriversResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/drivers/{id}": {
            "get": {
                "description": "Obtiene la información de un conductor específico con su perfil y turnos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conductores"
                ],
                "summary": "Obtener conductor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del conductor (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Información del conductor",
                        "schema": {
                            "$ref": "#/definitions/handlers.DriverResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Conductor no encontrado",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Actualiza la información básica de un conductor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conductores"
                ],
                "summary": "Actualizar conductor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del conductor (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateDriverRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conductor actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.DriverResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o ID inválido",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Conductor no encontrado",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un conductor (solo si no tiene turnos activos)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conductores"
                ],
                "summary": "Eliminar conductor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del conductor (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conductor eliminado exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "ID inválido o conductor con turnos activos",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Conductor no encontrado",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/drivers/{id}/profile": {
            "put": {
                "description": "Actualiza las preferencias y permisos del perfil de operador",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conductores"
                ],
                "summary": "Actualizar perfil de operador",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del conductor (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del perfil a actualizar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateOperatorProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Perfil actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.OperatorProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o ID inválido",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Conductor o perfil no encontrado",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/drivers/{id}/stats": {
            "get": {
                "description": "Obtiene estadísticas de turnos y actividad de un conductor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conductores"
                ],
                "summary": "Obtener estadísticas de conductor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del conductor (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Estadísticas del conductor",
                        "schema": {
                            "$ref": "#/definitions/handlers.DriverStatsResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Conductor no encontrado",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/shifts/clock-in": {
            "post": {
                "description": "Registra el inicio de turno de un conductor con un camión asignado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Turnos"
                ],
                "summary": "Iniciar turno (Clock-in)",
                "parameters": [
                    {
                        "description": "Datos del clock-in",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ClockInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Turno iniciado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.ClockInResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o ID de conductor inválido",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Conductor no encontrado o Camión no encontrado",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "El conductor ya tiene un turno activo o El camión no está disponible",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/shifts/clock-out": {
            "post": {
                "description": "Registra el fin de turno de un conductor, liberando el camión",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Turnos"
                ],
                "summary": "Finalizar turno (Clock-out)",
                "parameters": [
                    {
                        "description": "Datos del clock-out",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ClockOutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Turno finalizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.ClockOutResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o ID de conductor inválido",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No se encontró un turno activo para este conductor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/trucks": {
            "get": {
                "description": "Obtiene la lista de todos los camiones con filtros opcionales",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Camiones"
                ],
                "summary": "Listar camiones",
                "parameters": [
                    {
                        "enum": [
                            "DISPONIBLE",
                            "EN_USO",
                            "MANTENIMIENTO"
                        ],
                        "type": "string",
                        "description": "Filtrar por estado",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "CARGA_LATERAL",
                            "CARGA_POSTERIOR"
                        ],
                        "type": "string",
                        "description": "Filtrar por tipo",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de camiones",
                        "schema": {
                            "$ref": "#/definitions/handlers.ListTrucksResponse"
                        }
                    },
                    "400": {
                        "description": "Parámetros inválidos",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Registra un nuevo camión en la flota",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Camiones"
                ],
                "summary": "Crear camión",
                "parameters": [
                    {
                        "description": "Datos del camión",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateTruckRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Camión creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.TruckResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o placa duplicada",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/trucks/{id}": {
            "get": {
                "description": "Obtiene la información de un camión específico por ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Camiones"
                ],
                "summary": "Obtener camión",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del camión",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Información del camión",
                        "schema": {
                            "$ref": "#/definitions/handlers.TruckResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Camión no encontrado",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Actualiza la información de un camión existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Camiones"
                ],
                "summary": "Actualizar camión",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del camión",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateTruckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Camión actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.TruckResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o ID inválido",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Camión no encontrado",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un camión de la flota (solo si no tiene turnos activos)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Camiones"
                ],
                "summary": "Eliminar camión",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del camión",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Camión eliminado exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "ID inválido o camión con turnos activos",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Camión no encontrado",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ActiveShiftResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "650e8400-e29b-41d4-a716-446655440099"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "start_time": {
                    "type": "string",
                    "example": "2024-01-15T08:00:00Z"
                },
                "truck_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handlers.ClockInRequest": {
            "type": "object",
            "required": [
                "driver_id",
                "truck_plate"
            ],
            "properties": {
                "driver_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "truck_plate": {
                    "type": "string",
                    "example": "ABC-1234"
                }
            }
        },
        "handlers.ClockInResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Turno iniciado exitosamente"
                },
                "shift_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440099"
                }
            }
        },
        "handlers.ClockOutRequest": {
            "type": "object",
            "required": [
                "driver_id"
            ],
            "properties": {
                "driver_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "handlers.ClockOutResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Turno finalizado exitosamente"
                }
            }
        },
        "handlers.CreateTruckRequest": {
            "type": "object",
            "required": [
                "plate",
                "type"
            ],
            "properties": {
                "plate": {
                    "type": "string",
                    "example": "ABC-1234"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TruckStatus"
                        }
                    ],
                    "example": "DISPONIBLE"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TruckType"
                        }
                    ],
                    "example": "CARGA_LATERAL"
                }
            }
        },
        "handlers.DriverResponse": {
            "type": "object",
            "properties": {
                "active_shifts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ActiveShiftResponse"
                    }
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "full_name": {
                    "type": "string",
                    "example": "Juan Pérez"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "operator_profile": {
                    "$ref": "#/definitions/handlers.OperatorProfileResponse"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.DriverStatus"
                        }
                    ],
                    "example": "DISPONIBLE"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "handlers.DriverStatsResponse": {
            "type": "object",
            "properties": {
                "active_shifts": {
                    "type": "integer",
                    "example": 1
                },
                "completed_shifts": {
                    "type": "integer",
                    "example": 24
                },
                "driver_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "full_name": {
                    "type": "string",
                    "example": "Juan Pérez"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.DriverStatus"
                        }
                    ],
                    "example": "DISPONIBLE"
                },
                "total_shifts": {
                    "type": "integer",
                    "example": 25
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Mensaje de error descriptivo"
                }
            }
        },
        "handlers.ListDriversResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 5
                },
                "drivers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.DriverResponse"
                    }
                }
            }
        },
        "handlers.ListTrucksResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 5
                },
                "trucks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.TruckResponse"
                    }
                }
            }
        },
        "handlers.OperatorProfileResponse": {
            "type": "object",
            "properties": {
                "can_drive_lateral": {
                    "type": "boolean",
                    "example": true
                },
                "can_drive_posterior": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "preferred_zone_id": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "handlers.TruckResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "plate": {
                    "type": "string",
                    "example": "ABC-1234"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TruckStatus"
                        }
                    ],
                    "example": "DISPONIBLE"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TruckType"
                        }
                    ],
                    "example": "CARGA_LATERAL"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "handlers.UpdateDriverRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Juan Pérez"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.DriverStatus"
                        }
                    ],
                    "example": "DISPONIBLE"
                }
            }
        },
        "handlers.UpdateOperatorProfileRequest": {
            "type": "object",
            "properties": {
                "can_drive_lateral": {
                    "type": "boolean",
                    "example": true
                },
                "can_drive_posterior": {
                    "type": "boolean",
                    "example": false
                },
                "preferred_zone_id": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "handlers.UpdateTruckRequest": {
            "type": "object",
            "properties": {
                "plate": {
                    "type": "string",
                    "example": "XYZ-5678"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TruckStatus"
                        }
                    ],
                    "example": "MANTENIMIENTO"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TruckType"
                        }
                    ],
                    "example": "CARGA_POSTERIOR"
                }
            }
        },
        "models.DriverStatus": {
            "type": "string",
            "enum": [
                "OFFLINE",
                "DISPONIBLE",
                "OCUPADO"
            ],
            "x-enum-varnames": [
                "DriverStatusOffline",
                "DriverStatusDisponible",
                "DriverStatusOcupado"
            ]
        },
        "models.TruckStatus": {
            "type": "string",
            "enum": [
                "DISPONIBLE",
                "EN_USO",
                "MANTENIMIENTO"
            ],
            "x-enum-varnames": [
                "TruckStatusDisponible",
                "TruckStatusEnUso",
                "TruckStatusMantenimiento"
            ]
        },
        "models.TruckType": {
            "type": "string",
            "enum": [
                "CARGA_LATERAL",
                "CARGA_POSTERIOR"
            ],
            "x-enum-varnames": [
                "TruckTypeCargaLateral",
                "TruckTypeCargaPosterior"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8084",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Fleet Service API",
	Description:      "API para gestión de flota de camiones, conductores y turnos",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
