package main

// @title Auth Service API
// @version 1.0
// @description Servicio de autenticación (registro, login) para la aplicación.
// @contact.name API Support
// @contact.email support@example.com
// @host localhost:8080
// @BasePath /

import (
	"log"
	"os"

	"github.com/Andres09xZ/latacunga_clean_app/internal/database"
	"github.com/Andres09xZ/latacunga_clean_app/internal/models"
	"github.com/Andres09xZ/latacunga_clean_app/internal/server"
	"github.com/joho/godotenv"

	// docs is generated by swag and must be imported so the router can serve doc.json
	_ "github.com/Andres09xZ/latacunga_clean_app/docs"
)

func main() {
	// Intentar cargar .env desde distintas ubicaciones para facilitar ejecuciones desde subcarpetas
	if err := godotenv.Load(); err != nil {
		// intentar carpeta padre (ej. cmd/)
		if err2 := godotenv.Load("../.env"); err2 != nil {
			// intentar dos niveles arriba
			_ = godotenv.Load("../../.env")
		}
	}

	// Si DB_URL no está presente, informar al usuario con instrucción clara
	if os.Getenv("DB_URL") == "" {
		log.Fatal("DB_URL environment variable is not set. Add it to your environment or to a .env file at the repository root.")
	}

	// Connect to DB and run migrations before starting the HTTP server
	database.Connect()
	if database.DB != nil {
		if err := database.DB.AutoMigrate(&models.User{}); err != nil {
			println("Error ejecutando migraciones:", err.Error())
		} else {
			println("Migracion de auth-service completada")
		}
	}

	server.Start()
}
