package main

import (
	"log"
	"os"

	"github.com/Andres09xZ/latacunga_clean_app/report-service/internal/server"
	"github.com/joho/godotenv"

	// docs is generated by swag and must be imported so the router can serve doc.json
	_ "github.com/Andres09xZ/latacunga_clean_app/report-service/docs"
)

// @title Report Service API
// @version 1.0
// @description Servicio para manejar reportes de usuarios.
// @host localhost:8081
// @BasePath /
func main() {
	// Load .env
	if err := godotenv.Load(); err != nil {
		// intentar carpeta padre (ej. cmd/)
		if err2 := godotenv.Load("../.env"); err2 != nil {
			// intentar dos niveles arriba
			_ = godotenv.Load("../../.env")
		}
	}

	// Si DB_URL no está presente, informar al usuario con instrucción clara
	if os.Getenv("DB_URL") == "" {
		log.Fatal("DB_URL environment variable is not set. Add it to your environment or to a .env file at the repository root.")
	}

	server.Start()
}
