// Code generated by swaggo/swag. DO NOT EDIT.
package docs

import (
	"github.com/swaggo/swag"
)

const docTemplate = `{
    "schemes": [
        "http"
    ],
    "swagger": "2.0",
    "info": {
        "description": "API for route optimization and management",
        "title": "Route Service API",
        "version": "1.0"
    },
    "host": "localhost:8084",
    "basePath": "/",
    "paths": {
        "/api/v1/routes/generate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generate an optimized route for an operator on a specific date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Generate optimized route",
                "parameters": [
                    {
                        "description": "Route creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateRouteRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Idempotency key for deduplication",
                        "name": "Idempotency-Key",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.RouteResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Route already exists or being generated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/routes/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a route by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Get route by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Route ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RouteResponse"
                        }
                    },
                    "404": {
                        "description": "Route not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/routes/{operator_id}/{date}/steps": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all steps for an operator's route on a specific date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Get route steps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operator ID",
                        "name": "operator_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Work date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RouteStepResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Route not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateRouteRequest": {
            "type": "object",
            "required": [
                "operator_id",
                "work_date"
            ],
            "properties": {
                "operator_id": {
                    "type": "string"
                },
                "shift_id": {
                    "type": "string"
                },
                "task_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "work_date": {
                    "type": "string"
                }
            }
        },
        "models.RouteResponse": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "integer"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "operator_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RouteStep"
                    }
                },
                "work_date": {
                    "type": "string"
                }
            }
        },
        "models.RouteStep": {
            "type": "object",
            "properties": {
                "arrival_eta": {
                    "type": "string"
                },
                "departure_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "leg_distance_m": {
                    "type": "integer"
                },
                "leg_duration_s": {
                    "type": "integer"
                },
                "route_id": {
                    "type": "string"
                },
                "seq": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "models.RouteStepResponse": {
            "type": "object",
            "properties": {
                "arrival_eta": {
                    "type": "string"
                },
                "departure_time": {
                    "type": "string"
                },
                "leg_distance_m": {
                    "type": "integer"
                },
                "leg_duration_s": {
                    "type": "integer"
                },
                "seq": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	return docTemplate
}

// Swagger implements the swag.Swagger interface
func (s *s) Swagger() *swaggerInfo {
	return &SwaggerInfo
}

func init() {
	swag.Register(swag.Name, &s{})
}
