// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://latacunga.gob.ec/terms/",
        "contact": {
            "name": "API Support",
            "email": "soporte@latacunga.gob.ec"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/planning/config/thresholds": {
            "put": {
                "description": "Permite configurar dinámicamente los umbrales que activan la recolección automática",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Planning"
                ],
                "summary": "Actualiza umbrales de disparo por zona",
                "parameters": [
                    {
                        "description": "Mapa de zona a umbral (ej: {\\",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cantidad de umbrales actualizados",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "JSON inválido o umbral negativo",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/planning/simulate": {
            "post": {
                "description": "Inyecta un incidente falso con coordenadas para verificar detección de zona y acumulación de puntaje",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Planning"
                ],
                "summary": "Simula un incidente para debugging",
                "parameters": [
                    {
                        "description": "Datos del incidente simulado",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SimulateIncidentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Umbral superado, recolección activada automáticamente",
                        "schema": {
                            "$ref": "#/definitions/models.PlanningResult"
                        }
                    },
                    "202": {
                        "description": "Incidente procesado, zona detectada, puntaje acumulado (umbral no superado)",
                        "schema": {
                            "$ref": "#/definitions/models.PlanningResult"
                        }
                    },
                    "400": {
                        "description": "Coordenadas inválidas o zona no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/planning/zones": {
            "get": {
                "description": "Obtiene todas las zonas macro de planificación con su geometría y configuración de horario",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Planning"
                ],
                "summary": "Lista todas las zonas de recolección",
                "responses": {
                    "200": {
                        "description": "Lista de zonas",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/planning/zones/{id}/metrics": {
            "get": {
                "description": "Retorna el puntaje actual y umbral configurado para una zona específica",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Planning"
                ],
                "summary": "Obtiene métricas de acumulación de una zona",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la zona",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Métricas de la zona",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Zona o métricas no encontradas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/planning/zones/{id}/trigger": {
            "post": {
                "description": "Fuerza un trigger de recolección ignorando el puntaje acumulado, útil para emergencias",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Planning"
                ],
                "summary": "Dispara manualmente la recolección para una zona",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la zona",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Razón del trigger manual (ej: {\\",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Resultado del trigger",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "JSON inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Verifica la salud de RabbitMQ y otros componentes del sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Verifica la salud de todos los servicios",
                "responses": {
                    "200": {
                        "description": "Todos los servicios están saludables",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Uno o más servicios no están disponibles",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/health/rabbitmq": {
            "get": {
                "description": "Verifica la conexión y estado de RabbitMQ",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Verifica la salud de RabbitMQ",
                "responses": {
                    "200": {
                        "description": "RabbitMQ está saludable",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "RabbitMQ no está disponible",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/handlers.ServiceInfo"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "handlers.ServiceInfo": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.PlanningResult": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                },
                "scheduled_label": {
                    "type": "string"
                },
                "scheduled_time": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "threshold": {
                    "type": "integer"
                },
                "triggered": {
                    "type": "boolean"
                },
                "zone_id": {
                    "type": "integer"
                },
                "zone_name": {
                    "type": "string"
                }
            }
        },
        "models.SimulateIncidentRequest": {
            "type": "object",
            "required": [
                "lat",
                "lon",
                "type"
            ],
            "properties": {
                "lat": {
                    "description": "Centro de URBANO_CENTRAL",
                    "type": "number",
                    "example": -0.935
                },
                "lon": {
                    "description": "Centro de URBANO_CENTRAL",
                    "type": "number",
                    "example": -78.6175
                },
                "type": {
                    "type": "string",
                    "example": "SENSOR_LLENO"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Schedule Service - Planning Core API",
	Description:      "API de planificación para recolección de residuos de Latacunga. Geolocaliza incidentes, acumula puntaje y dispara eventos de recolección.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
